document.addEventListener('DOMContentLoaded', () => {
    
    // 1. Initialize Map
    const map = L.map('map').setView([26.78, 75.82], 11);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; OpenStreetMap contributors | LandIntel'
    }).addTo(map);

    const infraLayer = L.layerGroup().addTo(map);
    const landLayer = L.layerGroup().addTo(map);
    L.control.layers(null, {"🏗️ Govt Infrastructure": infraLayer, "📍 Land Listings": landLayer}, { collapsed: false }).addTo(map);

    let globalListings = [];

    // 2. Fetch data generated by Python Scraper
    // Note: Using explicit relative path './data.json'
    fetch('./data.json')
        .then(response => {
            if (!response.ok) throw new Error("Could not load data.json");
            return response.json();
        })
        .then(data => {
            // Update UI timestamp
            document.getElementById('lastUpdated').innerText = data.last_updated;
            globalListings = data.listings;
            
            // Render Infrastructure
            data.infrastructure.forEach(item => {
                const marker = L.circleMarker([item.lat, item.lng], { color: '#c0392b', fillColor: '#e74c3c', fillOpacity: 0.8, radius: 8, weight: 2 });
                marker.bindPopup(`
                    <div class="popup-title" style="color:#c0392b;">🏗️ ${item.name}</div>
                    <div class="popup-detail"><strong>Status:</strong> ${item.status}</div>
                    <div class="popup-detail"><em>${item.desc}</em></div>
                `);
                infraLayer.addLayer(marker);
            });

            renderListings();
        })
        .catch(error => {
            console.error(error);
            document.getElementById('lastUpdated').innerText = "Fetch Error (Check Console)";
        });

    // 3. Render Listings Function
    function renderListings() {
        landLayer.clearLayers();
        const priceFilter = document.getElementById('priceFilter').value;

        globalListings.forEach((item, index) => {
            if (priceFilter === 'under100' && item.price >= 100) return;
            if (priceFilter === 'over100' && item.price < 100) return;

            const marker = L.marker([item.lat, item.lng]);
            marker.bindPopup(`
                <div class="popup-title">📍 ${item.title}</div>
                <div class="popup-detail"><strong>Price:</strong> ${item.priceTxt}</div>
                <div class="popup-detail" style="margin-bottom:8px;"><em>${item.desc}</em></div>
                <button class="btn-primary" onclick="openReport(${index})">View Real AI Report</button>
            `);
            landLayer.addLayer(marker);
        });
    }

    // 4. Global Modal Function
    window.openReport = function(index) {
        const ai = globalListings[index].ai_report;
        const sourcesHtml = ai.sources.map(src => `<span style="display:inline-block; background:#ecf0f1; padding:3px 6px; border-radius:4px; font-size:11px; margin:2px 5px 2px 0; border:1px solid #bdc3c7;">📄 ${src}</span>`).join('');

        const htmlContent = `
            <div style="display:grid; grid-template-columns: 1fr 1fr; gap:10px; margin-bottom:15px;">
                <div style="background:#f8f9fa; padding:10px; border-radius:6px; border:1px solid #e9ecef;">
                    <h4 style="margin:0 0 5px 0; font-size:11px; color:#7f8c8d; text-transform:uppercase;">Certainty</h4>
                    <p style="margin:0; font-weight:bold; font-size:14px;">${ai.certaintyScore}</p>
                </div>
                <div style="background:#f8f9fa; padding:10px; border-radius:6px; border:1px solid #e9ecef;">
                    <h4 style="margin:0 0 5px 0; font-size:11px; color:#7f8c8d; text-transform:uppercase;">Habitation</h4>
                    <p style="margin:0; font-weight:bold; font-size:14px;">${ai.civilization}</p>
                </div>
            </div>
            <div style="margin-bottom:15px;"><h3 style="font-size:14px; margin:0 0 5px 0; color:#2980b9;">🏗️ Infra Reality Check</h3><p style="margin:0; font-size:13px;">${ai.projectStatus}</p></div>
            <div style="margin-bottom:15px;"><h3 style="font-size:14px; margin:0 0 5px 0; color:#2980b9;">⚖️ Zoning & Legal Risk</h3><p style="margin:0; font-size:13px;">${ai.zoningRisk}</p></div>
            <div style="margin-bottom:15px;"><h3 style="font-size:14px; margin:0 0 5px 0; color:#2980b9;">💡 Optimal Land Use</h3><p style="margin:0; font-size:13px;">${ai.bestUse}</p></div>
            <div style="background:#f0f3f4; padding:10px; border-radius:6px;">
                <h3 style="font-size:11px; margin:0 0 5px 0; color:#7f8c8d;">DATA LINEAGE (SCRAPED SOURCES)</h3>
                <div>${sourcesHtml}</div>
            </div>
        `;
        document.getElementById('modalBodyContent').innerHTML = htmlContent;
        document.getElementById('aiModal').style.display = 'flex';
    };

    // Close Modal Event
    document.getElementById('closeModalBtn').addEventListener('click', () => {
        document.getElementById('aiModal').style.display = 'none';
    });

    // Filter Event
    document.getElementById('priceFilter').addEventListener('change', renderListings);
});